provider: openai

models:
    default: gpt-4o-mini
    supervisor: gpt-4o-mini
    planner: gpt-4o-mini
    worker: gpt-4o-mini
    reviewer: gpt-4o-mini

# provider: openrouter

# models:
#     default: liquid/lfm-2.5-1.2b-instruct:free
#     planner: liquid/lfm-2.5-1.2b-instruct:free
#     worker: liquid/lfm-2.5-1.2b-instruct:free
#     reviewer: liquid/lfm-2.5-1.2b-instruct:free

llm:
    max_retries: 10

runtime:
    supervisor_max_retries: 3
    planner_max_tool_steps: 10
    worker_max_tool_steps: 10
    reviewer_max_tool_steps: 10

tools:
    supervisor: []
    planner:
        - list_files
        - search
    worker:
        - bash
        - read_file
        - search
        - list_files
        - apply_patch
    reviewer:
        - read_file
        - search
        - list_files
        - git_diff
